# Generated by Django 4.1.4 on 2022-12-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
                ('created_date', models.DateTimeField()),
                ('file_name', models.CharField(blank=True, max_length=30, null=True)),
                ('total_records', models.IntegerField()),
                ('total_created', models.IntegerField(blank=True, null=True)),
                ('total_errors', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
